spring:
  profiles:
  application:
    name: tweet-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
twitsec:
  rabbitmq:
    tweetqueue: tweet.queue

server:
  port: 49501

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:api
    username: sa